### ISSUE TITLE
calling 'view' with no arguments results in panic

### ISSUE THREAD

**Issue by particledecay** [particledecay/kconf#4]
```sh
➜ kconf view
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/particledecay/kconf/cmd.glob..func8(0x1013c60, 0x1047040, 0x0, 0x0)
	/home/joelinux/Projects/kconf/cmd/kconf.go:122 +0x221
github.com/spf13/cobra.(*Command).execute(0x1013c60, 0x1047040, 0x0, 0x0, 0x1013c60, 0x1047040)
	/home/joelinux/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x1013260, 0xc0000f5db8, 0x1, 0x1)
	/home/joelinux/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/home/joelinux/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/particledecay/kconf/cmd.Execute()
	/home/joelinux/Projects/kconf/cmd/kconf.go:150 +0x135
main.main()
	/home/joelinux/Projects/kconf/main.go:18 +0x1c3
```

Just need to add a function to the Cobra command view definition for checking the args.

**Comment by particledecay** [comment]
Fixed in [988ec9b96db33e646d2afa7b906937baef578db2](https://github.com/particledecay/kconf/commit/988ec9b96db33e646d2afa7b906937baef578db2). Closing.
